### ISSUE TITLE
Bug with different text size and texture atlas

### ISSUE THREAD

**Issue by Reuh** [xerpi/sftdlib#1]
Since 7671870074694d5a3692361b7ca945a5760f3390, there is a problem when drawing text in differents sizes.

The texture atlas stores and retrieve characters without checking the current text size, so, for example, if we call `sftd_draw_text(font, x, y, color, 10, "he")` and then `sftd_draw_text(font, x, y, color, 30, "hello")`, the second call will draw "he" in size 10 (caracters stored in the texture atlas in the first call) and "llo" in size 30.

This results in some weird mix of text sizes.

**Comment by xerpi** [comment]
Yes, that's right. I'll try to solve it by storing the current size of the glyph in the atlas, and then applying scale.

**Comment by xerpi** [comment]
Solved with 2f2b384278513c4564bc02b1d3de83fbf1e6eeea.
