### ISSUE TITLE
Sample not working as intended

### ISSUE THREAD

**Issue by hax0kartik** [xerpi/sftdlib#14]
I compiled the sample but when i try to open it the program it simply cuts the tops screen diagonally into two halves One is white in color and the other one is black.The bottom screen is half red and half black

**Comment by SonyUSA** [comment]
It did work at one point, however Xerpi told me these libraries are deprecated and he no longer supports them :/

**Comment by xerpi** [comment]
It works fine for me (tested in both Citra and 3DS).
Are you using the latest versions of citro3d, sf2d and sftd from github?

**Comment by hax0kartik** [comment]
Looks somehow i borked my sf2dlib.Works now.Thanks.
