### ISSUE TITLE
Weird behavior after loading & freeing font multiple times

### ISSUE THREAD

**Issue by georgesofianosgr** [xerpi/sftdlib#4]
I'm trying to figure out what is wrong with my game engine,
I'm not sure if I'm doing something wrong or this is a bug.

I created a simple example based on the library's sample that reproduces the problem.
After running 9 times load_font_file and then freed the font, my game crashes. 
The font that I load and free multiple times is the same font file.

This is the code: https://gist.github.com/geocool/57bb71e6a8c4a4250d63
And this is the result : 
![capture](https://cloud.githubusercontent.com/assets/2379934/9934754/e7606ada-5d5b-11e5-9fc5-ba00251282e3.PNG)

**Comment by xerpi** [comment]
I guess I'm leaking memory somewhere, I'll check the load_font_file function.

**Comment by xerpi** [comment]
Fixed with bdee6f33eca7e85c2eaf5018c52e2852facfae86.
