### ISSUE TITLE
sftd_get_text_width's text parameter isn't marked "const"

### ISSUE THREAD

**Issue by flarn2006** [xerpi/sftdlib#7]
Looking at sftd.c, it doesn't look like `sftd_get_text_width` modifies the string pointed to by its `text` parameter in any way, nor can I think of any situation in which it would make sense for it to do so. When dealing with strings, however, making sure parameters are marked `const` is very important, as otherwise, for instance, string literals don't work. The C++ `std::string` class also can't be used here, as its `c_str` method returns a `const` string. As a result, I had to use the ugly workaround of putting `const_cast<char*>(text.c_str())` instead of simply `text.c_str()`.

**Comment by xerpi** [comment]
Yeah, I'll add const right now. Good catch.

**Comment by xerpi** [comment]
Fixed with 8199133185919ac9c2e06f86b7733e0644c1d7ae.
